# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
peptides: "config/peptides.txt"
msfragger_peptides_tsv: "config/peptide.tsv"
ground_truth: "resources/kleiner_ground_truth-equal_protein-full_taxid_lineage.csv"
unipept_result: "resources/unipept_results-Kleiner_P_msfragger.csv"
