$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# forbid usage of parameters beyond the ones defined in this schema
additionalProperties: false

# possible entries of the config file and which type they should be
properties:
  query_dbs:
    type: array
    items:
      type: string
    description: "protein sequence databases to use for sequence alignment and megadudes"
  alignment_methods:
    type: array
    items:
      type: string
    description: "Methods to use for sequence alignment of input fastas against reference databases"

# entries that have to be in the config file for successful validation
required:
  - query_dbs
  - alignment_methods
