name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  UnitTesting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: install package
      run: conda install --yes --quiet -c bioconda -c conda-forge snakemake-minimal mamba pytest
    - name: test
      run: pytest

#  IntegrationTesting:
#    runs-on: ubuntu-latest
#    needs: Linting
#    steps:
#    - uses: actions/checkout@v2
#    - name: Test workflow (local test data)
#      uses: snakemake/snakemake-github-action@v1
#      with:
#        directory: test/integration
#        snakefile: workflow/Snakefile
#        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs"
#    - name: Test report
#      uses: snakemake/snakemake-github-action@v1
#      with:
#        directory: test/integration
#        snakefile: workflow/Snakefile
#        args: "--report report.zip"
